### DISCUSSION TITLE
Define DNS Server

### DISCUSSION THREAD

**Discussion by ricamz** [caarlos0/domain_exporter#246] [Ideas]
Hi there.

Is it possible do define the dns server where the query is made?

Regards

Ricardo

**Comment by caarlos0** [comment]
its in the readme

```yaml
domains:
- google.com
- name: reddit.com        # <--- the domain to query
  host: whois.godaddy.com # <--- this is the custom server
```
