### ISSUE TITLE
.ai domains Unable to resolve

### ISSUE THREAD

**Issue by cdq502** [caarlos0/domain_exporter#195]
Unable to resolve domain names with the .ai suffix. I also used the “--config=domains.yaml” parameter, but it does not work. Can users directly specify the host to resolve in the whois command using the -h option?

I have set the following in prometheus.yml: 
```
  - job_name: domain
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: localhost:9222 # domain_exporter address
    static_configs:
      - targets:
        - google.com
```
domains.yaml:
```
domains:
- baidu.com
- name: wondershare.ai
  host: whois.godaddy.com
```
The startup command is set as follows: 

```
nohup domain_exporter --config=domains.yaml &
```

Am I using it incorrectly?

**Comment by cdq502** [comment]
Most .ai domain names cannot be resolved directly using the whois command. I used your custom specified HOST method, but it did not work, so I am reporting it to you. Please check if there is a problem with my usage. Thank you.

**Comment by cdq502** [comment]
> copied the wrong command earlier:
> 
> ```
> $ whois -h whois.godaddy.com wondershare.ai
> No match for "wondershare.ai" in the registrar database.
> ```
> 
> that said, in your prometheus.yml, you either remove the `targets google.com` thing and get only `/metrics`, or add it there with the host as well, so the url should be `http://localhost:9222/probe?target=chatgpt.ai&host=whois.godaddy.com`.
> 
> The difference is that, if you query from `/metrics`, results are cached, if you use `/probe`, they aren't.

 I see that it cannot be executed and still returns a domain expiration time of -1. Because I need to use it with the Grafana panel, I have also tried : 
```
  - job_name: domain
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: localhost:9222 # domain_exporter address
```
domains.yaml
```
domains:
- google.com
- name: chatgpt.ai
  host: whois.godaddy.com
```
startup
```
nohup ./domain_exporter --config=domains.yaml &
```
 Unfortunately, I still cannot successfully obtain the domain expiration time. wondershare.ai is an example. Most .ai domain names need to specify whois.godaddy.com to correctly find the expiration time. It’s just that I can’t achieve this in the domains.yml you provided. Can you provide a complete setup method?

**Comment by caarlos0** [comment]
```
  - job_name: domain
    metrics_path: /metrics # <- change here
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: localhost:9222 # domain_exporter address
```
