### ISSUE TITLE
compose

### ISSUE THREAD

**Issue by juanpvh** [caarlos0/domain_exporter#20]
Aew Carlos Blz?!
É possivel rodar o domain_exporter com docker-compose?
Se tiver um exemplo como aplicar, agradeço.
Ainda estou estudando docker e prometheus :)

vlw, abraço.

**Comment by caarlos0** [comment]
Opa, algo assim:

```yaml
services:
  domain_exporter:
    image: caarlos0/domain_exporter:v1.3.0
    restart: always
    ports:
    - 9222:9222
```

deve funcionar :)
